// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: api/proto/metrics.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetMetricsRequest specifies parameters for metrics collection
type GetMetricsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Interval in seconds - how often to send snapshots
	IntervalSeconds int32 `protobuf:"varint,1,opt,name=interval_seconds,json=intervalSeconds,proto3" json:"interval_seconds,omitempty"`
	// Averaging window in seconds - over what period to average metrics
	AveragingWindowSeconds int32 `protobuf:"varint,2,opt,name=averaging_window_seconds,json=averagingWindowSeconds,proto3" json:"averaging_window_seconds,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetMetricsRequest) Reset() {
	*x = GetMetricsRequest{}
	mi := &file_api_proto_metrics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricsRequest) ProtoMessage() {}

func (x *GetMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_metrics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetMetricsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_metrics_proto_rawDescGZIP(), []int{0}
}

func (x *GetMetricsRequest) GetIntervalSeconds() int32 {
	if x != nil {
		return x.IntervalSeconds
	}
	return 0
}

func (x *GetMetricsRequest) GetAveragingWindowSeconds() int32 {
	if x != nil {
		return x.AveragingWindowSeconds
	}
	return 0
}

// MetricsSnapshot contains all collected system metrics
type MetricsSnapshot struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Timestamp when snapshot was taken (Unix timestamp)
	Timestamp int64 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Load average metrics
	LoadAverage *LoadAverage `protobuf:"bytes,2,opt,name=load_average,json=loadAverage,proto3" json:"load_average,omitempty"`
	// CPU metrics
	Cpu *CPUMetrics `protobuf:"bytes,3,opt,name=cpu,proto3" json:"cpu,omitempty"`
	// Disk I/O metrics
	Disk *DiskMetrics `protobuf:"bytes,4,opt,name=disk,proto3" json:"disk,omitempty"`
	// Filesystem information
	Filesystem *FilesystemInfo `protobuf:"bytes,5,opt,name=filesystem,proto3" json:"filesystem,omitempty"`
	// Network statistics
	Network *NetworkStats `protobuf:"bytes,6,opt,name=network,proto3" json:"network,omitempty"`
	// Socket statistics
	Sockets       *SocketStats `protobuf:"bytes,7,opt,name=sockets,proto3" json:"sockets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsSnapshot) Reset() {
	*x = MetricsSnapshot{}
	mi := &file_api_proto_metrics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsSnapshot) ProtoMessage() {}

func (x *MetricsSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_metrics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsSnapshot.ProtoReflect.Descriptor instead.
func (*MetricsSnapshot) Descriptor() ([]byte, []int) {
	return file_api_proto_metrics_proto_rawDescGZIP(), []int{1}
}

func (x *MetricsSnapshot) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *MetricsSnapshot) GetLoadAverage() *LoadAverage {
	if x != nil {
		return x.LoadAverage
	}
	return nil
}

func (x *MetricsSnapshot) GetCpu() *CPUMetrics {
	if x != nil {
		return x.Cpu
	}
	return nil
}

func (x *MetricsSnapshot) GetDisk() *DiskMetrics {
	if x != nil {
		return x.Disk
	}
	return nil
}

func (x *MetricsSnapshot) GetFilesystem() *FilesystemInfo {
	if x != nil {
		return x.Filesystem
	}
	return nil
}

func (x *MetricsSnapshot) GetNetwork() *NetworkStats {
	if x != nil {
		return x.Network
	}
	return nil
}

func (x *MetricsSnapshot) GetSockets() *SocketStats {
	if x != nil {
		return x.Sockets
	}
	return nil
}

// LoadAverage contains system load average values
type LoadAverage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 1-minute load average
	Load1 float64 `protobuf:"fixed64,1,opt,name=load1,proto3" json:"load1,omitempty"`
	// 5-minute load average
	Load5 float64 `protobuf:"fixed64,2,opt,name=load5,proto3" json:"load5,omitempty"`
	// 15-minute load average
	Load15        float64 `protobuf:"fixed64,3,opt,name=load15,proto3" json:"load15,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadAverage) Reset() {
	*x = LoadAverage{}
	mi := &file_api_proto_metrics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadAverage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadAverage) ProtoMessage() {}

func (x *LoadAverage) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_metrics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadAverage.ProtoReflect.Descriptor instead.
func (*LoadAverage) Descriptor() ([]byte, []int) {
	return file_api_proto_metrics_proto_rawDescGZIP(), []int{2}
}

func (x *LoadAverage) GetLoad1() float64 {
	if x != nil {
		return x.Load1
	}
	return 0
}

func (x *LoadAverage) GetLoad5() float64 {
	if x != nil {
		return x.Load5
	}
	return 0
}

func (x *LoadAverage) GetLoad15() float64 {
	if x != nil {
		return x.Load15
	}
	return 0
}

// CPUMetrics contains CPU usage statistics
type CPUMetrics struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Percentage of time spent in user mode
	UserPercent float64 `protobuf:"fixed64,1,opt,name=user_percent,json=userPercent,proto3" json:"user_percent,omitempty"`
	// Percentage of time spent in system mode
	SystemPercent float64 `protobuf:"fixed64,2,opt,name=system_percent,json=systemPercent,proto3" json:"system_percent,omitempty"`
	// Percentage of time idle
	IdlePercent   float64 `protobuf:"fixed64,3,opt,name=idle_percent,json=idlePercent,proto3" json:"idle_percent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CPUMetrics) Reset() {
	*x = CPUMetrics{}
	mi := &file_api_proto_metrics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CPUMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CPUMetrics) ProtoMessage() {}

func (x *CPUMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_metrics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CPUMetrics.ProtoReflect.Descriptor instead.
func (*CPUMetrics) Descriptor() ([]byte, []int) {
	return file_api_proto_metrics_proto_rawDescGZIP(), []int{3}
}

func (x *CPUMetrics) GetUserPercent() float64 {
	if x != nil {
		return x.UserPercent
	}
	return 0
}

func (x *CPUMetrics) GetSystemPercent() float64 {
	if x != nil {
		return x.SystemPercent
	}
	return 0
}

func (x *CPUMetrics) GetIdlePercent() float64 {
	if x != nil {
		return x.IdlePercent
	}
	return 0
}

// DiskMetrics contains disk I/O statistics
type DiskMetrics struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Transfers per second
	Tps float64 `protobuf:"fixed64,1,opt,name=tps,proto3" json:"tps,omitempty"`
	// Kilobytes per second (read + write)
	KbPerSec float64 `protobuf:"fixed64,2,opt,name=kb_per_sec,json=kbPerSec,proto3" json:"kb_per_sec,omitempty"`
	// Per-disk statistics
	Disks         []*DiskStats `protobuf:"bytes,3,rep,name=disks,proto3" json:"disks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiskMetrics) Reset() {
	*x = DiskMetrics{}
	mi := &file_api_proto_metrics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskMetrics) ProtoMessage() {}

func (x *DiskMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_metrics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskMetrics.ProtoReflect.Descriptor instead.
func (*DiskMetrics) Descriptor() ([]byte, []int) {
	return file_api_proto_metrics_proto_rawDescGZIP(), []int{4}
}

func (x *DiskMetrics) GetTps() float64 {
	if x != nil {
		return x.Tps
	}
	return 0
}

func (x *DiskMetrics) GetKbPerSec() float64 {
	if x != nil {
		return x.KbPerSec
	}
	return 0
}

func (x *DiskMetrics) GetDisks() []*DiskStats {
	if x != nil {
		return x.Disks
	}
	return nil
}

// DiskStats contains statistics for a single disk
type DiskStats struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Disk device name (e.g., "sda", "nvme0n1")
	Device string `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	// Transfers per second for this disk
	Tps float64 `protobuf:"fixed64,2,opt,name=tps,proto3" json:"tps,omitempty"`
	// Kilobytes per second for this disk
	KbPerSec      float64 `protobuf:"fixed64,3,opt,name=kb_per_sec,json=kbPerSec,proto3" json:"kb_per_sec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiskStats) Reset() {
	*x = DiskStats{}
	mi := &file_api_proto_metrics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskStats) ProtoMessage() {}

func (x *DiskStats) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_metrics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskStats.ProtoReflect.Descriptor instead.
func (*DiskStats) Descriptor() ([]byte, []int) {
	return file_api_proto_metrics_proto_rawDescGZIP(), []int{5}
}

func (x *DiskStats) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *DiskStats) GetTps() float64 {
	if x != nil {
		return x.Tps
	}
	return 0
}

func (x *DiskStats) GetKbPerSec() float64 {
	if x != nil {
		return x.KbPerSec
	}
	return 0
}

// FilesystemInfo contains filesystem usage information
type FilesystemInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Per-filesystem statistics
	Filesystems   []*FilesystemStats `protobuf:"bytes,1,rep,name=filesystems,proto3" json:"filesystems,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilesystemInfo) Reset() {
	*x = FilesystemInfo{}
	mi := &file_api_proto_metrics_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilesystemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilesystemInfo) ProtoMessage() {}

func (x *FilesystemInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_metrics_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilesystemInfo.ProtoReflect.Descriptor instead.
func (*FilesystemInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_metrics_proto_rawDescGZIP(), []int{6}
}

func (x *FilesystemInfo) GetFilesystems() []*FilesystemStats {
	if x != nil {
		return x.Filesystems
	}
	return nil
}

// FilesystemStats contains statistics for a single filesystem
type FilesystemStats struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Filesystem mount point
	MountPoint string `protobuf:"bytes,1,opt,name=mount_point,json=mountPoint,proto3" json:"mount_point,omitempty"`
	// Used space in megabytes
	UsedMb int64 `protobuf:"varint,2,opt,name=used_mb,json=usedMb,proto3" json:"used_mb,omitempty"`
	// Percentage of space used
	UsedPercent float64 `protobuf:"fixed64,3,opt,name=used_percent,json=usedPercent,proto3" json:"used_percent,omitempty"`
	// Used inodes
	UsedInodes int64 `protobuf:"varint,4,opt,name=used_inodes,json=usedInodes,proto3" json:"used_inodes,omitempty"`
	// Percentage of inodes used
	InodesPercent float64 `protobuf:"fixed64,5,opt,name=inodes_percent,json=inodesPercent,proto3" json:"inodes_percent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilesystemStats) Reset() {
	*x = FilesystemStats{}
	mi := &file_api_proto_metrics_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilesystemStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilesystemStats) ProtoMessage() {}

func (x *FilesystemStats) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_metrics_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilesystemStats.ProtoReflect.Descriptor instead.
func (*FilesystemStats) Descriptor() ([]byte, []int) {
	return file_api_proto_metrics_proto_rawDescGZIP(), []int{7}
}

func (x *FilesystemStats) GetMountPoint() string {
	if x != nil {
		return x.MountPoint
	}
	return ""
}

func (x *FilesystemStats) GetUsedMb() int64 {
	if x != nil {
		return x.UsedMb
	}
	return 0
}

func (x *FilesystemStats) GetUsedPercent() float64 {
	if x != nil {
		return x.UsedPercent
	}
	return 0
}

func (x *FilesystemStats) GetUsedInodes() int64 {
	if x != nil {
		return x.UsedInodes
	}
	return 0
}

func (x *FilesystemStats) GetInodesPercent() float64 {
	if x != nil {
		return x.InodesPercent
	}
	return 0
}

// NetworkStats contains network statistics
type NetworkStats struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Top talkers by protocol
	ProtocolStats []*ProtocolStats `protobuf:"bytes,1,rep,name=protocol_stats,json=protocolStats,proto3" json:"protocol_stats,omitempty"`
	// Top talkers by traffic (source:port -> dest:port)
	TrafficStats  []*TrafficStats `protobuf:"bytes,2,rep,name=traffic_stats,json=trafficStats,proto3" json:"traffic_stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkStats) Reset() {
	*x = NetworkStats{}
	mi := &file_api_proto_metrics_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkStats) ProtoMessage() {}

func (x *NetworkStats) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_metrics_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkStats.ProtoReflect.Descriptor instead.
func (*NetworkStats) Descriptor() ([]byte, []int) {
	return file_api_proto_metrics_proto_rawDescGZIP(), []int{8}
}

func (x *NetworkStats) GetProtocolStats() []*ProtocolStats {
	if x != nil {
		return x.ProtocolStats
	}
	return nil
}

func (x *NetworkStats) GetTrafficStats() []*TrafficStats {
	if x != nil {
		return x.TrafficStats
	}
	return nil
}

// ProtocolStats contains statistics for a network protocol
type ProtocolStats struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Protocol name (TCP, UDP, ICMP, etc.)
	Protocol string `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	// Total bytes transferred
	Bytes int64 `protobuf:"varint,2,opt,name=bytes,proto3" json:"bytes,omitempty"`
	// Percentage of total bytes
	Percent       float64 `protobuf:"fixed64,3,opt,name=percent,proto3" json:"percent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtocolStats) Reset() {
	*x = ProtocolStats{}
	mi := &file_api_proto_metrics_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtocolStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtocolStats) ProtoMessage() {}

func (x *ProtocolStats) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_metrics_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtocolStats.ProtoReflect.Descriptor instead.
func (*ProtocolStats) Descriptor() ([]byte, []int) {
	return file_api_proto_metrics_proto_rawDescGZIP(), []int{9}
}

func (x *ProtocolStats) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *ProtocolStats) GetBytes() int64 {
	if x != nil {
		return x.Bytes
	}
	return 0
}

func (x *ProtocolStats) GetPercent() float64 {
	if x != nil {
		return x.Percent
	}
	return 0
}

// TrafficStats contains statistics for network traffic
type TrafficStats struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Source IP:port
	Source string `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	// Destination IP:port
	Destination string `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	// Protocol
	Protocol string `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
	// Bytes per second
	BytesPerSecond float64 `protobuf:"fixed64,4,opt,name=bytes_per_second,json=bytesPerSecond,proto3" json:"bytes_per_second,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TrafficStats) Reset() {
	*x = TrafficStats{}
	mi := &file_api_proto_metrics_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficStats) ProtoMessage() {}

func (x *TrafficStats) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_metrics_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficStats.ProtoReflect.Descriptor instead.
func (*TrafficStats) Descriptor() ([]byte, []int) {
	return file_api_proto_metrics_proto_rawDescGZIP(), []int{10}
}

func (x *TrafficStats) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *TrafficStats) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *TrafficStats) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *TrafficStats) GetBytesPerSecond() float64 {
	if x != nil {
		return x.BytesPerSecond
	}
	return 0
}

// SocketStats contains socket statistics
type SocketStats struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Listening sockets
	ListeningSockets []*ListeningSocket `protobuf:"bytes,1,rep,name=listening_sockets,json=listeningSockets,proto3" json:"listening_sockets,omitempty"`
	// TCP connection states
	TcpStates     *TCPConnectionStates `protobuf:"bytes,2,opt,name=tcp_states,json=tcpStates,proto3" json:"tcp_states,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SocketStats) Reset() {
	*x = SocketStats{}
	mi := &file_api_proto_metrics_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SocketStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SocketStats) ProtoMessage() {}

func (x *SocketStats) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_metrics_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SocketStats.ProtoReflect.Descriptor instead.
func (*SocketStats) Descriptor() ([]byte, []int) {
	return file_api_proto_metrics_proto_rawDescGZIP(), []int{11}
}

func (x *SocketStats) GetListeningSockets() []*ListeningSocket {
	if x != nil {
		return x.ListeningSockets
	}
	return nil
}

func (x *SocketStats) GetTcpStates() *TCPConnectionStates {
	if x != nil {
		return x.TcpStates
	}
	return nil
}

// ListeningSocket represents a listening socket
type ListeningSocket struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Process command name
	Command string `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	// Process ID
	Pid int32 `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	// User name
	User string `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	// Protocol (TCP, UDP)
	Protocol string `protobuf:"bytes,4,opt,name=protocol,proto3" json:"protocol,omitempty"`
	// Port number
	Port          int32 `protobuf:"varint,5,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListeningSocket) Reset() {
	*x = ListeningSocket{}
	mi := &file_api_proto_metrics_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListeningSocket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListeningSocket) ProtoMessage() {}

func (x *ListeningSocket) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_metrics_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListeningSocket.ProtoReflect.Descriptor instead.
func (*ListeningSocket) Descriptor() ([]byte, []int) {
	return file_api_proto_metrics_proto_rawDescGZIP(), []int{12}
}

func (x *ListeningSocket) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ListeningSocket) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ListeningSocket) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *ListeningSocket) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *ListeningSocket) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

// TCPConnectionStates contains counts of TCP connections by state
type TCPConnectionStates struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of connections in ESTABLISHED state
	Established int32 `protobuf:"varint,1,opt,name=established,proto3" json:"established,omitempty"`
	// Number of connections in FIN_WAIT state
	FinWait int32 `protobuf:"varint,2,opt,name=fin_wait,json=finWait,proto3" json:"fin_wait,omitempty"`
	// Number of connections in SYN_RECEIVED state
	SynReceived int32 `protobuf:"varint,3,opt,name=syn_received,json=synReceived,proto3" json:"syn_received,omitempty"`
	// Number of connections in TIME_WAIT state
	TimeWait int32 `protobuf:"varint,4,opt,name=time_wait,json=timeWait,proto3" json:"time_wait,omitempty"`
	// Number of connections in CLOSE_WAIT state
	CloseWait int32 `protobuf:"varint,5,opt,name=close_wait,json=closeWait,proto3" json:"close_wait,omitempty"`
	// Number of connections in other states
	Other         int32 `protobuf:"varint,6,opt,name=other,proto3" json:"other,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TCPConnectionStates) Reset() {
	*x = TCPConnectionStates{}
	mi := &file_api_proto_metrics_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TCPConnectionStates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TCPConnectionStates) ProtoMessage() {}

func (x *TCPConnectionStates) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_metrics_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TCPConnectionStates.ProtoReflect.Descriptor instead.
func (*TCPConnectionStates) Descriptor() ([]byte, []int) {
	return file_api_proto_metrics_proto_rawDescGZIP(), []int{13}
}

func (x *TCPConnectionStates) GetEstablished() int32 {
	if x != nil {
		return x.Established
	}
	return 0
}

func (x *TCPConnectionStates) GetFinWait() int32 {
	if x != nil {
		return x.FinWait
	}
	return 0
}

func (x *TCPConnectionStates) GetSynReceived() int32 {
	if x != nil {
		return x.SynReceived
	}
	return 0
}

func (x *TCPConnectionStates) GetTimeWait() int32 {
	if x != nil {
		return x.TimeWait
	}
	return 0
}

func (x *TCPConnectionStates) GetCloseWait() int32 {
	if x != nil {
		return x.CloseWait
	}
	return 0
}

func (x *TCPConnectionStates) GetOther() int32 {
	if x != nil {
		return x.Other
	}
	return 0
}

var File_api_proto_metrics_proto protoreflect.FileDescriptor

const file_api_proto_metrics_proto_rawDesc = "" +
	"\n" +
	"\x17api/proto/metrics.proto\x12\ametrics\"x\n" +
	"\x11GetMetricsRequest\x12)\n" +
	"\x10interval_seconds\x18\x01 \x01(\x05R\x0fintervalSeconds\x128\n" +
	"\x18averaging_window_seconds\x18\x02 \x01(\x05R\x16averagingWindowSeconds\"\xd3\x02\n" +
	"\x0fMetricsSnapshot\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x127\n" +
	"\fload_average\x18\x02 \x01(\v2\x14.metrics.LoadAverageR\vloadAverage\x12%\n" +
	"\x03cpu\x18\x03 \x01(\v2\x13.metrics.CPUMetricsR\x03cpu\x12(\n" +
	"\x04disk\x18\x04 \x01(\v2\x14.metrics.DiskMetricsR\x04disk\x127\n" +
	"\n" +
	"filesystem\x18\x05 \x01(\v2\x17.metrics.FilesystemInfoR\n" +
	"filesystem\x12/\n" +
	"\anetwork\x18\x06 \x01(\v2\x15.metrics.NetworkStatsR\anetwork\x12.\n" +
	"\asockets\x18\a \x01(\v2\x14.metrics.SocketStatsR\asockets\"Q\n" +
	"\vLoadAverage\x12\x14\n" +
	"\x05load1\x18\x01 \x01(\x01R\x05load1\x12\x14\n" +
	"\x05load5\x18\x02 \x01(\x01R\x05load5\x12\x16\n" +
	"\x06load15\x18\x03 \x01(\x01R\x06load15\"y\n" +
	"\n" +
	"CPUMetrics\x12!\n" +
	"\fuser_percent\x18\x01 \x01(\x01R\vuserPercent\x12%\n" +
	"\x0esystem_percent\x18\x02 \x01(\x01R\rsystemPercent\x12!\n" +
	"\fidle_percent\x18\x03 \x01(\x01R\vidlePercent\"g\n" +
	"\vDiskMetrics\x12\x10\n" +
	"\x03tps\x18\x01 \x01(\x01R\x03tps\x12\x1c\n" +
	"\n" +
	"kb_per_sec\x18\x02 \x01(\x01R\bkbPerSec\x12(\n" +
	"\x05disks\x18\x03 \x03(\v2\x12.metrics.DiskStatsR\x05disks\"S\n" +
	"\tDiskStats\x12\x16\n" +
	"\x06device\x18\x01 \x01(\tR\x06device\x12\x10\n" +
	"\x03tps\x18\x02 \x01(\x01R\x03tps\x12\x1c\n" +
	"\n" +
	"kb_per_sec\x18\x03 \x01(\x01R\bkbPerSec\"L\n" +
	"\x0eFilesystemInfo\x12:\n" +
	"\vfilesystems\x18\x01 \x03(\v2\x18.metrics.FilesystemStatsR\vfilesystems\"\xb6\x01\n" +
	"\x0fFilesystemStats\x12\x1f\n" +
	"\vmount_point\x18\x01 \x01(\tR\n" +
	"mountPoint\x12\x17\n" +
	"\aused_mb\x18\x02 \x01(\x03R\x06usedMb\x12!\n" +
	"\fused_percent\x18\x03 \x01(\x01R\vusedPercent\x12\x1f\n" +
	"\vused_inodes\x18\x04 \x01(\x03R\n" +
	"usedInodes\x12%\n" +
	"\x0einodes_percent\x18\x05 \x01(\x01R\rinodesPercent\"\x89\x01\n" +
	"\fNetworkStats\x12=\n" +
	"\x0eprotocol_stats\x18\x01 \x03(\v2\x16.metrics.ProtocolStatsR\rprotocolStats\x12:\n" +
	"\rtraffic_stats\x18\x02 \x03(\v2\x15.metrics.TrafficStatsR\ftrafficStats\"[\n" +
	"\rProtocolStats\x12\x1a\n" +
	"\bprotocol\x18\x01 \x01(\tR\bprotocol\x12\x14\n" +
	"\x05bytes\x18\x02 \x01(\x03R\x05bytes\x12\x18\n" +
	"\apercent\x18\x03 \x01(\x01R\apercent\"\x8e\x01\n" +
	"\fTrafficStats\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12 \n" +
	"\vdestination\x18\x02 \x01(\tR\vdestination\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\x12(\n" +
	"\x10bytes_per_second\x18\x04 \x01(\x01R\x0ebytesPerSecond\"\x91\x01\n" +
	"\vSocketStats\x12E\n" +
	"\x11listening_sockets\x18\x01 \x03(\v2\x18.metrics.ListeningSocketR\x10listeningSockets\x12;\n" +
	"\n" +
	"tcp_states\x18\x02 \x01(\v2\x1c.metrics.TCPConnectionStatesR\ttcpStates\"\x81\x01\n" +
	"\x0fListeningSocket\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\x05R\x03pid\x12\x12\n" +
	"\x04user\x18\x03 \x01(\tR\x04user\x12\x1a\n" +
	"\bprotocol\x18\x04 \x01(\tR\bprotocol\x12\x12\n" +
	"\x04port\x18\x05 \x01(\x05R\x04port\"\xc7\x01\n" +
	"\x13TCPConnectionStates\x12 \n" +
	"\vestablished\x18\x01 \x01(\x05R\vestablished\x12\x19\n" +
	"\bfin_wait\x18\x02 \x01(\x05R\afinWait\x12!\n" +
	"\fsyn_received\x18\x03 \x01(\x05R\vsynReceived\x12\x1b\n" +
	"\ttime_wait\x18\x04 \x01(\x05R\btimeWait\x12\x1d\n" +
	"\n" +
	"close_wait\x18\x05 \x01(\x05R\tcloseWait\x12\x14\n" +
	"\x05other\x18\x06 \x01(\x05R\x05other2U\n" +
	"\rSystemMonitor\x12D\n" +
	"\n" +
	"GetMetrics\x12\x1a.metrics.GetMetricsRequest\x1a\x18.metrics.MetricsSnapshot0\x01B7Z5github.com/IvanAndreevichPle/system-monitor/api/protob\x06proto3"

var (
	file_api_proto_metrics_proto_rawDescOnce sync.Once
	file_api_proto_metrics_proto_rawDescData []byte
)

func file_api_proto_metrics_proto_rawDescGZIP() []byte {
	file_api_proto_metrics_proto_rawDescOnce.Do(func() {
		file_api_proto_metrics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_metrics_proto_rawDesc), len(file_api_proto_metrics_proto_rawDesc)))
	})
	return file_api_proto_metrics_proto_rawDescData
}

var file_api_proto_metrics_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_api_proto_metrics_proto_goTypes = []any{
	(*GetMetricsRequest)(nil),   // 0: metrics.GetMetricsRequest
	(*MetricsSnapshot)(nil),     // 1: metrics.MetricsSnapshot
	(*LoadAverage)(nil),         // 2: metrics.LoadAverage
	(*CPUMetrics)(nil),          // 3: metrics.CPUMetrics
	(*DiskMetrics)(nil),         // 4: metrics.DiskMetrics
	(*DiskStats)(nil),           // 5: metrics.DiskStats
	(*FilesystemInfo)(nil),      // 6: metrics.FilesystemInfo
	(*FilesystemStats)(nil),     // 7: metrics.FilesystemStats
	(*NetworkStats)(nil),        // 8: metrics.NetworkStats
	(*ProtocolStats)(nil),       // 9: metrics.ProtocolStats
	(*TrafficStats)(nil),        // 10: metrics.TrafficStats
	(*SocketStats)(nil),         // 11: metrics.SocketStats
	(*ListeningSocket)(nil),     // 12: metrics.ListeningSocket
	(*TCPConnectionStates)(nil), // 13: metrics.TCPConnectionStates
}
var file_api_proto_metrics_proto_depIdxs = []int32{
	2,  // 0: metrics.MetricsSnapshot.load_average:type_name -> metrics.LoadAverage
	3,  // 1: metrics.MetricsSnapshot.cpu:type_name -> metrics.CPUMetrics
	4,  // 2: metrics.MetricsSnapshot.disk:type_name -> metrics.DiskMetrics
	6,  // 3: metrics.MetricsSnapshot.filesystem:type_name -> metrics.FilesystemInfo
	8,  // 4: metrics.MetricsSnapshot.network:type_name -> metrics.NetworkStats
	11, // 5: metrics.MetricsSnapshot.sockets:type_name -> metrics.SocketStats
	5,  // 6: metrics.DiskMetrics.disks:type_name -> metrics.DiskStats
	7,  // 7: metrics.FilesystemInfo.filesystems:type_name -> metrics.FilesystemStats
	9,  // 8: metrics.NetworkStats.protocol_stats:type_name -> metrics.ProtocolStats
	10, // 9: metrics.NetworkStats.traffic_stats:type_name -> metrics.TrafficStats
	12, // 10: metrics.SocketStats.listening_sockets:type_name -> metrics.ListeningSocket
	13, // 11: metrics.SocketStats.tcp_states:type_name -> metrics.TCPConnectionStates
	0,  // 12: metrics.SystemMonitor.GetMetrics:input_type -> metrics.GetMetricsRequest
	1,  // 13: metrics.SystemMonitor.GetMetrics:output_type -> metrics.MetricsSnapshot
	13, // [13:14] is the sub-list for method output_type
	12, // [12:13] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_api_proto_metrics_proto_init() }
func file_api_proto_metrics_proto_init() {
	if File_api_proto_metrics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_metrics_proto_rawDesc), len(file_api_proto_metrics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_metrics_proto_goTypes,
		DependencyIndexes: file_api_proto_metrics_proto_depIdxs,
		MessageInfos:      file_api_proto_metrics_proto_msgTypes,
	}.Build()
	File_api_proto_metrics_proto = out.File
	file_api_proto_metrics_proto_goTypes = nil
	file_api_proto_metrics_proto_depIdxs = nil
}
