// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: api/proto/metrics.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SystemMonitor_GetMetrics_FullMethodName = "/metrics.SystemMonitor/GetMetrics"
)

// SystemMonitorClient is the client API for SystemMonitor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SystemMonitor service provides system metrics via server-side streaming
type SystemMonitorClient interface {
	// GetMetrics streams system metrics to clients
	// Client specifies interval (N seconds) and averaging window (M seconds)
	GetMetrics(ctx context.Context, in *GetMetricsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MetricsSnapshot], error)
}

type systemMonitorClient struct {
	cc grpc.ClientConnInterface
}

func NewSystemMonitorClient(cc grpc.ClientConnInterface) SystemMonitorClient {
	return &systemMonitorClient{cc}
}

func (c *systemMonitorClient) GetMetrics(ctx context.Context, in *GetMetricsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MetricsSnapshot], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SystemMonitor_ServiceDesc.Streams[0], SystemMonitor_GetMetrics_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetMetricsRequest, MetricsSnapshot]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SystemMonitor_GetMetricsClient = grpc.ServerStreamingClient[MetricsSnapshot]

// SystemMonitorServer is the server API for SystemMonitor service.
// All implementations must embed UnimplementedSystemMonitorServer
// for forward compatibility.
//
// SystemMonitor service provides system metrics via server-side streaming
type SystemMonitorServer interface {
	// GetMetrics streams system metrics to clients
	// Client specifies interval (N seconds) and averaging window (M seconds)
	GetMetrics(*GetMetricsRequest, grpc.ServerStreamingServer[MetricsSnapshot]) error
	mustEmbedUnimplementedSystemMonitorServer()
}

// UnimplementedSystemMonitorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSystemMonitorServer struct{}

func (UnimplementedSystemMonitorServer) GetMetrics(*GetMetricsRequest, grpc.ServerStreamingServer[MetricsSnapshot]) error {
	return status.Errorf(codes.Unimplemented, "method GetMetrics not implemented")
}
func (UnimplementedSystemMonitorServer) mustEmbedUnimplementedSystemMonitorServer() {}
func (UnimplementedSystemMonitorServer) testEmbeddedByValue()                       {}

// UnsafeSystemMonitorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SystemMonitorServer will
// result in compilation errors.
type UnsafeSystemMonitorServer interface {
	mustEmbedUnimplementedSystemMonitorServer()
}

func RegisterSystemMonitorServer(s grpc.ServiceRegistrar, srv SystemMonitorServer) {
	// If the following call pancis, it indicates UnimplementedSystemMonitorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SystemMonitor_ServiceDesc, srv)
}

func _SystemMonitor_GetMetrics_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetMetricsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SystemMonitorServer).GetMetrics(m, &grpc.GenericServerStream[GetMetricsRequest, MetricsSnapshot]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SystemMonitor_GetMetricsServer = grpc.ServerStreamingServer[MetricsSnapshot]

// SystemMonitor_ServiceDesc is the grpc.ServiceDesc for SystemMonitor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SystemMonitor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "metrics.SystemMonitor",
	HandlerType: (*SystemMonitorServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetMetrics",
			Handler:       _SystemMonitor_GetMetrics_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/proto/metrics.proto",
}
